version: '2'

services:
  # cuda:
  #   restart: always
  #   build: ./CUDA
  #   privileged: true

  # opencv:
  #   restart: always
  #   build: ./OPENCV
  #   privileged: true

  roscore:
    container_name: master
    build: ./ROS/CORE
    command: roscore

  talker:
    container_name: talker
    build:
      context: ./ROS/TALKER
      dockerfile: Dockerfile
    command: rosrun roscpp_tutorials talker
    environment:
      - ROS_HOSTNAME=talker
      - ROS_MASTER_URI=http://master:11311

  listener:
    container_name: listner
    build: ./ROS/LISTENER
    command: rosrun roscpp_tutorials listner
    environment:
      - ROS_HOSTNAME=listner
      - ROS_MASTER_URI=http://master:11311
